### ISSUE TITLE
death messages: player names disappear

### ISSUE THREAD

**Issue by CREEATION** [advancedfx/advancedfx-prop#1]
Hello,

when viewing any demo with HLAE, the player names in the death messages disappear.
Only the weapon and headshot icons show up ("killed with"):

![hlaebug03](https://cloud.githubusercontent.com/assets/3277769/8766238/dbc1a1d6-2e2f-11e5-902b-a94b26770a92.jpg)

However, when starting CS without HLAE the names appear normally:

![hlaebug02](https://cloud.githubusercontent.com/assets/3277769/8766223/5a37f9da-2e2f-11e5-834c-1789a37a71ea.jpg)

My settings:

![hlaebug01](https://cloud.githubusercontent.com/assets/3277769/8766228/64e03ac8-2e2f-11e5-804b-57be8ed46ff2.jpg)

I didn't use any "mirv" commands or anything, all standard. No demo tools used for fixes.
Any hints on this?

**Comment by dtugend** [comment]
Hello.

This is very strange.
Which HLAE Version are you using?
Is it possible to upload a demo with the problem?
Do you have any moviemaking commands in autoexec.cfg or s.th. like that?

**Comment by dtugend** [comment]
Also try this with HLAE

playdemo &lt;demoName&gt;
disconnect
viewdemo &lt;demoName&gt;

Chances are nothing is broken, but that without HLAE you joined a server beforehand or played a different demo (especially when using COL DemoPlayer in default settings).

Meaning it could be a viewdemo bug, when you view the demo the first time. (There is a bug with playernames not appearing the first round sometimes, which can be fixed by loading the demo in playdemo beforehand).

**Comment by CREEATION** [comment]
Hello,

I'm using the latest HLAE version. Also all demos are effected.
I only specified an alias in my autoexec.cfg which I didn't use when viewing the demo, so I doubt this could be the problem.
HLAE is the only tool I'm using, no other Demo-Player btw.
I'll try your solution later, thanks for the feedback and this awesome tool :)

**Comment by dtugend** [comment]
Would be great if you could provide me with the demo, in case the problem is HLAE specific.

**Comment by dtugend** [comment]
Also are you using juGGaKNot's new or old MovieMaking pack by any Chance?
I talked to him and we just noticed there seems to be a problem (not related to HLAE) when using the pack.

Or are you using any other moviemaking pack?

**Comment by CREEATION** [comment]
Using blank CS without any moviemaking related stuff.
Demo: http://www.file-upload.net/download-10778993/thisismydemomydemoisamazing.zip.html
Also not fixed after a complete computer restart. But I noticed that it worked when I first used HLAE... and then it suddenly broke.

**Comment by dtugend** [comment]
Hello.

I had a look at the demo and it got a known problem **whether or not** HLAE is used:

**How to reproduce it:**
1) **Freshly** start the game (doesn't matter if with HLAE or not)
2) viewdemo yourDemoNameHerre

**Symptom:**
Before the next round start, the player names are missing like on your screenshot.

**Workaround:**
Let the demo play until the first recorded round start, then rewind it (preferred) or restart it. This should fix the problem in _most_ cases.

If no round start is recorded in the demo:
Sometimes it also helps to start a listenserver beforehand in the game, but I usually don't recommend that:
- Listenservers should not be used with HLAE (though listenservers usually don't have VAC and I use them for testing with HLAE sometimes, but still don't recommend it - if you join a real server accidentally with HLAE, then you will get most likely VAC banned, that is why HLAE issues a warning before allowing to join any server)
- It will still be bugged (i.e. grey names instead of T/CT colour), the workaround above is much better (if applicable)

<br />
As said this is a known problem with the way the game records and reads data from demos. There is not much I can do about that (I don't have enough demo format knowledge to write s.th. that fixes the demo, i.e. by adding a fake round start right at the start).

_Please check if you can confirm that it is not an HLAE related problem and if the workaround above works for you._

**Comment by CREEATION** [comment]
Thanks again!
But if it's not HLAE related, why can I see all names normally when starting CS without HLAE and viewing the demo?
I'll try your workaround later, thanks for your investigations :)

**Comment by CREEATION** [comment]
So, the workaround isn't working. Still no names showing up, tried it multiple times.
As I said, without HLAE it works as it should with all demos, so it must be something related to HLAE.
I hope I can help you to further investigate this. Seems like I'm having a different problem here than the one you described ;(
It seems a bit odd that it worked for some time and then it suddenly broke in HLAE.

**Comment by dtugend** [comment]
Hm that's really odd.

Well the problem is HLAE should do nothing to the death messages unless you execute mirv_deathmsg the first time.

Is the path your are launching CS with the same as the path your Steam installation uses? Maybe you have two installations of CS (one on C: and one on D:) and are using an modified / old one (on D:)?

I can only offer to have a look at your Installation / PC through TeamViewer, you can contact me in #hlae, check http://www.advancedfx.org/contact/ for webchat.

**Comment by dtugend** [comment]
You an also add me on Steam if you want in order to contact me: http://steamcommunity.com/id/ripieces/

I tried to search you there but only found an account that was online over an year ago :/

**Comment by dtugend** [comment]
Okay, the workaround works.

There was a different problem:
The height was bellow 480 pixels, for this case there is no EngineFont defined in `C:\Program Files (x86)\Steam\steamapps\common\Half-Life\platform\resource\TracherScheme.res`, that is why the workaround did not work for @CREEATION 

I will add a warning box for users that set bellow 480 pixels in the launcher with one of the next updates and when it's released I'll close the issue :-)

**Comment by CREEATION** [comment]
Thanks for resolving this issue :)
Isn't the width also affected?

**Comment by dtugend** [comment]
Thank you.
This issue has been addressed in HLAE 2.4.9.0 (2015-07-23T16:00Z).
Thus closing.

Edit: regarding the height: most values should not cause such a problem.
