### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by kriswema** [advancedfx/advancedfx-prop#13]
Are there any plans to support Linux in the future? The GitHub statistics said most of the code is C++ and C, but I bet there are some Windows-specific parts that might not be (easily) replaceable.

**Comment by dtugend** [comment]
There are no plans for support of Linux in the future as of now.

While I would like to see a Linux and maybe even MacOS port, it's beyond my resources to support one at the moment:
- The detours code is highly OS dependant.
- The hooks in AfxHookGoldSrc are highly dependant on a specific build, since most of it is static binary patching.
- The hooks in AfxHookSource are highly dependant on a specifc compiler, because the offsets from the locations that are found depend on the compiler. Also the hooking / wrapping / detouring of Valve's C++ classes is highly compiler dependant, since many of them are not pure interfaces or even have multiple inheritance involved, meaning the actual memory layout depends on the compiler.
- The AfxHook.dat / AfxCppCli injection code is highly OS dependant (this one is the minor problem it would have to be rewritten for any OS anyways.)

**Comment by dtugend** [comment]
Linux support is very unlikely at the moment, thus closing the issue until this decision is revisited (unlikely).
