### ISSUE TITLE
Crashing in Left 4 Dead 2

### ISSUE THREAD

**Issue by SerDIDG** [advancedfx/advancedfx-prop#23]
Hi. Any chance to start HLAE with Left 4 Dead 2? Thanks.

**Comment by dtugend** [comment]
Hello, thank you for your bug report.

The problem is the VEngineCvar007 interface in HLAE was adjusted for CS:GO and L4D2 uses the same interface version, but it's different.

It's not hard to fix that, but it would take a very notable amount of time. However currently other things have priority (not only HLAE related), so I cannot give an estimate when it will be fixed and you should not count on / wait for it being fixed any time soon.

(The game Alien Swarm should be affected as well.)

**Comment by SerDIDG** [comment]
Sad, but still thank you for a great job!

**Comment by lank1z** [comment]
u didnt fixed yet? cuz i have the same problem

**Comment by dtugend** [comment]
> u didnt fixed yet? cuz i have the same problem

No, not yet.

**Comment by lank1z** [comment]
i hope u'll fix it soon, cuz i have great idea to edit l4d2 xD

**Comment by dtugend** [comment]
I looked into the [hl2sdk / L4D2 SDK by AlliedModders](https://github.com/alliedmodders/hl2sdk/tree/l4d2).

Basically it doesn't match the Alien Swarm SDK in the relevant areas. So I'd need to make an adjustment specifically for L4D2.

**So my question is:** Is it worth it for you, since it **would only include non-CS:GO specific features**, which are listed with "several" and _might_ include features listed as "CS:GO + ?" in the [AfxHookSource Commands overview table (link)](https://github.com/ripieces/advancedfx/wiki/Source%3ACommands#command-list)?

**Comment by lank1z** [comment]
yeah

**Comment by Veprod** [comment]
Hello i am l4d1 and l4d2 editor, and i am working on my last project. I really need any advice with saving demo to .agr so i could use it in blender. As far as i know it's possible only with hlae in cs go. :(

**Comment by dtugend** [comment]
I am sorry to disappoint you: HLAE supports agr only with CS:GO and I am not planning to extend that support to other games at the moment.

**Comment by lank1z** [comment]
its still crashing when im trying to start l4d2 with hlae...

**Comment by dtugend** [comment]
I haven't come around to implementing this so far, this is why this issue still is open.

Please not that the repository path (name) of the issue changed due to reorganizing things, the issue is not lost, just somewhere else now.

**Comment by dtugend** [comment]
This issue will be closed when fixed and the issue tracker removed from this old sub repository.
If the issue persists after that, please open an issue in the [new main repo](https://github.com/advancedfx/advancedfx) or use the existing [issue #25 in new main repo](https://github.com/advancedfx/advancedfx/issues/25).
Don't forget to update to the latest version when the issue is fixed.
