### ISSUE TITLE
GOTV demos crash at start-up 

### ISSUE THREAD

**Issue by nicohenmax** [advancedfx/advancedfx-prop#24]
GOTV Demos crash at start-up, no matter if the game is in windowed ; fullscreen-windowed or fullscreen. 

please fix this ASAP, it is really important

**Comment by dtugend** [comment]
Please make sure that your game is fully updated and verify the cache and try again,  both with HLAE 2.14.8 and without. 

If the problem persists for HLAE only please provide an GOTV demo with the problem.

**Comment by dtugend** [comment]
Please also try if it is caused by some specific mirv_ command in your movie making config, maybe only a specific HLAE feature that you use is broken, that causes a crash upon loading a demo.

It's a bit suspicious, because if the problem would affect many people, I'd usually get reports also on forum and Twitter by other people.

So please make sure to provide the GOTV demo, so I can try to reproduce the problem.

**Comment by dtugend** [comment]
Hello, you didn't reply since more than 20 days, I cannot solve the issue without your assistance, so please reply soon if it's fixed or otherwise I will close this issue.

**Comment by twinplay** [comment]
Hi, had the same problem after I closed Counter Strike while recording. The DemoFix-Tool didn't helped me or I couldn't find out how it's used :D. Simply redownloading HLAE fixed the issue.

**Comment by dtugend** [comment]
Closing due to lacking feedback (cannot solve without).
