### ISSUE TITLE
CS:GO - Rename Teams

### ISSUE THREAD

**Issue by DarrenRainey** [advancedfx/advancedfx-prop#25]
How can I rename teams in my demo files to make it look like a pro game

**Comment by dtugend** [comment]
If you mean this:
![CS:GO Team Display at screen top](http://puu.sh/rEmTd/3fa615ce11.jpg)
While it's theoretically possible, HLAE doesn't support it and I am not planning to add it.

What you can do is use to hide the that team display
<tt>cl_draw_only_deathnotices 1</tt>
and use
[mirv_replace_name](https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_replace_name) to change the full player name in the deathnotices / ... (i.e. add/remove tags / fake player names / ...)

Please close this issue if you don't have further questions, otherwise I will close it in a few days myself.

**Comment by DarrenRainey** [comment]
ok :( I guess ill record without the hud and manually add in the score overlays
