### ISSUE TITLE
CS 1.6 crashing, when using HLAE

### ISSUE THREAD

**Issue by soQlSpeedrun** [advancedfx/advancedfx-prop#30]
I've got a problem to set more than.. some, things to do, by mirv.
When i create more than.. 20? 25? things, like STUFFTEXT, or CAMPATH or another, then game suddenly crashes and all of my work is gone. Is that possible to fix that?
Idk, maybe maximum number of "things" is 16 and i didn't know that, or sth?
Thanks.

**Comment by dtugend** [comment]
The number of DemoEdit events you can have in a demo is not that tightly limited, it must be s.th. specific that makes the demo crash.

Sometimes the demo does simply not work with DemoEdit, meaning if you let it finish loading (**"Demo file completely loaded. Disconnected. Automatic connection retry"**  is printed in console then), it will always crash at some point (i.e. due to out of memory) regardless of what you do.

Please check if that's the case and report back.

If that's the case you can only use the demo without -demoedit, in order to avoid a crash.
You can still do some camera effects on those demos, since AfxHookGoldSrc has a rudimentary version of mirv_campath too.

**Comment by dtugend** [comment]
Closing due to no response in 9 days.
