### ISSUE TITLE
Wildcard support for "mirv_streams edit"

### ISSUE THREAD

**Issue by nkoep** [advancedfx/advancedfx-prop#32]
When editing streams, it could be handy to have a way to edit multiple streams at once. For instance, something along the lines of `mirv_streams edit \* stickerAction noDraw` to hide stickers on all streams would be very convenient. Ideally this would issue a warning to the console if it matches a stream which does not understand a property like `stickerAction`, e.g., depth streams (_I think_).

**Comment by dtugend** [comment]
Good suggestion, thanks for writing it down.

What we need to think about is how to handle alphaMatteEntity streams when mixed with normal streams, because those have their own logic and have sub-streams instead of the properties on the main stream and for it to make sense it would have to adjust both sub-streams at the same time with "some" logic applied, as you see things can get tricky very fast for those.
If it is okay, I'd implement it, without caring too much about incompatible streams, meaning if you have baseFx derived streams and alphaMatteEntity streams, then it will just spew some error messages, if you try to adjust them at the same time (because the sub-commands don't match).

(Btw.: Depth streams do have stickerAction since they are derived from "baseFx" streams. I.e. "normal" streams lack most options and for the combined alphaMatteEntity streams they are in the sub-streams as options.)
