### ISSUE TITLE
Map texture Error on Cache

### ISSUE THREAD

**Issue by Benb727** [advancedfx/advancedfx-prop#37]
When I try to watch my cache demo through HLAE, (which is fine watching it regularly), the map has missing or distorted textures and there are various red and black "ERROR" block around the map. I dont have any of the anti cheats, I restarted my game and verified game cache, I uninstall/reinstalled even with older versions. Only happens on the map Cache and only happens through HLAE. I just had a pistol headshot ace I want to edit/record :(((((((((((((((

**Comment by dtugend** [comment]
Please provide the demo.

**Comment by Benb727** [comment]
Now what recently started happening, whenever I load up my other demo of ANOTHER clip i want to record, my game closes after a few seconds. Im not running as an admin, and I've tried uninstalling/reinstalling and even trying older versions. But here is the demo link for the Cache clip 
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-7L9sj-PdD7v-ps6Ru-VdUE4-hBnUE

**Comment by Benb727** [comment]
Im trying to make my first frag movie and HLAE hates me :(((((((((

**Comment by dtugend** [comment]
I can confirm there are indeed some problems with mirv_streams, not sure if related to your problem, but I need to fix them and then we will see if your problem is fixed too.

**Comment by dtugend** [comment]
Does it still crash for you, since the latest 27th March 2017 CS:GO update?

**Comment by Benb727** [comment]
yes it does

**Comment by dtugend** [comment]
If possible, please email me a crash dump / link to it, my email is on my GitHub profile page now (please use some subject that allows to know that it's from you).

I recommend to not link it publicly, since it sometimes can contain sensitive information.

1) Make sure to use the latest HLAE version if possible, currenlty 2.25.2, please mention in your email which HLAE version you used, so I can check with the right symbol files for HLAE.
2) Please make sure the crash dump is actually from the time where the crash happened, since there might be multiple crash dumps.
3) The crash dump files are either in the folder where csgo.exe is (as .mdmp files) or in the C:\Program Files (x86)\Steam\dumps folder as .dmp files, please check both folders.

**Comment by Benb727** [comment]
I sent 3 dmp files in an email with the name HLAE from Benb727 (or something like that). thanks!

**Comment by dtugend** [comment]
I had a look at the crash dumps, they all crash in the same place.

The problem is, it might be surprising, but I am not sure if it's HLAE related at all, because the place they crash in, is actually for decoding network data from the demo stream, in "RecvTable_Decode" in engine.dll.

Please do the following:

1) Please check if you have any mirv_streams edit _streamNameHere_ attachCommands
or detachCommands in your config. If you have such a stream and have it in preview while loading a new demo, all sort of weird things can happen actually. The solution would be to end the preview of the stream (mirv_streams previewEnd) before loading a new demo for now.

2) Please describe the steps you do to load a new demo (commands you use etc.).

Edit: If you want you can send or link me your movie making config and I can check it for you, if you are unsure.

**Comment by dtugend** [comment]
I just found out that your CS:GO is actually outdated / not properly updated:
```
[...]
Build: 6661
[...]
version : 1.35.6.7
```

This build is from February or older.

This is a hint that your CS:GO installation is in an inconsistent state:

1) Make sure that you have updates enabled in Steam for CS:GO (right click in Steam library -> properties -> Updates Tab, make sure that "Always keep this game up to date" is enabled)

2) Verify the files of your installation: right click CS:GO in Steam library -> properties -> Local Files Tab -> Verify Integrity Of Game Cache button (let it verify and download files if required, will take a few minutes).

3) Make sure you are not using outdated addons (like SourceMod / ... ) for your CS:GO, rename or delete any "addon(s)" folder in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo

Last but not least, you might need to make sure you have the latest HLAE, because there was a CS:GO update today, and I yet need to check if s.th. is broken / try to fix newly broken things / make a new release.

**Comment by Benb727** [comment]
i did all you said, redownloaded hlae and all, and still crashes.

**Comment by Benb727** [comment]
i dont have a movie making config, hlae used to work fine and now it crashes any demo i try to look at.

**Comment by dtugend** [comment]
This is really weird, I can offer to have a look through AnyDesk or TeamViewer, please add me in Steam: https://steamcommunity.com/id/ripieces

**Comment by Benb727** [comment]
Hey I added you on Steam, my name is BennyS

**Comment by dtugend** [comment]
@Benb727 I think someone else had the same problem like you and we figured it out:

https://twitter.com/dtugend/status/865913794970734592

CS:GO bug (old): Start game with multicore rendering disabled, enable it, join a game or load a demo -> crash.

May not seem like a big deal at first, but if someone has mat_queue_mode changed through console / a config only, they will always crash.

Solution: Either enter mat_queue_mode 0 into console before loading a demo or fix mat_queue_mode to -1 in your video.txt (the one in userdata or if you use mmcfg folder the one in mmcfg folder).

**Comment by dtugend** [comment]
For solution see my previous comment.
Closing since you said earlier on Steam you don't bother anymore.
If that doesn't solve your problem, feel free to contact me in Steam or here.
