### ISSUE TITLE
CSGO Crashes

### ISSUE THREAD

**Issue by antim0118** [advancedfx/advancedfx-prop#44]
When i playing demo, csgo crashes (before new 2 csgo updates it was normal)

**Comment by dtugend** [comment]
Please do / check the following:

1) Right click csgo in Steam library and select Properties -> click LOCAL FILES tab -> click Verify Integrity of Game Cache button. Let it verify and if required re-download some files.

2) Make sure you are using the latest HLAE version.

3) If you have multiple installs of HLAE, people that use the Custom Loader instead of the recommended File -> Launch CS:GO dialogue sometimes make the mistake of selecting the AfxHookSource.dll of an old install of HLAE, please be extra sure to check that you are in the directory of the new HLAE when using the File Selection dialogue, because it tends to start in the old install folder sometimes I think.

4) If that doesn't help, please consider providing us with a download / link to the demo in question that causes the crash.


I am guessing it's most likely 3) though, or at least hope so.

**Comment by dtugend** [comment]
Since you didn't reply back within 7 days I consider this solved.
If that's not the case, please leave a reply.
