### ISSUE TITLE
mirv_deathmsg - non responsive/working.

### ISSUE THREAD

**Issue by JonTrooper** [advancedfx/advancedfx-prop#7]
I'm pretty new to HLAE but I've been trying to get mirv commands to work for example mirv_deathmsg, they appear in the console as autofill like they're there but when I enter them nothing happens no error or response. I've been asking everyone I know who uses HLAE but get no solution. Is it my side or could it be an issue here? And yes I have the latest version, reinstalled it twice.

Hope you could have an answer to this problem, thanks.
- I enter mirv_deathmsg debug 1, wait for someone to get a kill, no IDs or anything appears in the console.
- I'm using the AfxHookSource.dll
- CS:GO

**Comment by dtugend** [comment]
Hello, please provide the following info:

1) Enter <tt>version</tt> into console and copy and paste the console output here, here is mine:

```
] version
Protocol version 13499
Exe version 1.34.9.9 (csgo)
Exe build: 17:43:33 Jul 29 2015 (6102) (730)
```

Please keep in mind that this info will change when CS:GO is updated.

2) When you start the game HLAE should print some info into the console (you might need to scroll up), which could be helpful, here is mine:

```
|
| AfxHookSource (Aug 29 2015 07:47:51)
| http://advancedfx.org/
|
| VClient: VClient017 (CS:GO)
| VEngineClient: VEngineClient013
| VEngineCvar: VEngineCvar007
| GameDirectory: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo
| WrpConCommands::GetVEngineCvar007() == 0x61e020f0
|
```

The line with <tt>WrpConCommands::GetVEngineCvar007()</tt> will most likely differ, that is nothing to worry about.

3) What happens when you only enter <tt>mirv_deathmsg</tt>? It should print s.th. like this:

```
] mirv_deathmsg
Usage:
mirv_deathmsg block
mirv_deathmsg cfg
mirv_deathmsg debug
```

4) If you want to be sure we are using the same client.dll file (since that is where the deathmsg code HLAE hooks into lives), then you can use [QuickHask](https://github.com/tedsmith/quickhash/releases/latest) to compute a hash checksum and compare it with mine, this is mine:

```
File: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\bin\client.dll
SHA1: 05D3F753DDBA7FBCD83DA9623AF414A190DF0BD2
SHA512: 4B7CE62F9CD87A298C4A359AD3E36D94382ECE0126C5EF7B6EF089D792CE622C6DCFAD9C1C7673D8EAD92F8A327EB7277A9280C72E5BE28BE02A9B462919E777
```

Please keep in mind that this info will change when CS:GO is updated.

**Comment by JonTrooper** [comment]
1) I enter `version` into console, no output or response..

2) HLAE start up output.

```
|
| AfxHookSource (Aug 29 2015 07:47:51)
| http://advancedfx.org/
|
| VClient: VClient017 (CS:GO)
| VEngineClient: VEngineClient013
| VEngineCvar: VEngineCvar007
| GameDirectory: E:\SteamLibrary\SteamApps\common\Counter-Strike Global Offensive\csgo
| WrpConCommands::GetVEngineCvar007() == 0x5bf320f0
|
```

3)
![](http://puu.sh/k0XGY/d1d8ef6df3.png)

4) Having some major internet issues at the moment, couldn't get QuickHash to compute a hash checksum and compare it..

**Comment by dtugend** [comment]
Okay, the <tt>version</tt> command is not an HLAE command, if it doesn't produce any output, then there is a real problem, that is probably not HLAE related though.

First try if it's possible that it is related to your config (it's possible to fuck configs up by watching a certain demo (see [here](https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/401)):

1) Quit the game
2) Rename the csgo/cfg/config.cfg and csgo/cfg/autoexec.cfg config files to s.th. else
3) Start the game and see if the version command produces output, if it does s.th. is wrong with your config.

If that doesn't help:
1) Quit the game
2) rename the csgo/cfg folder to s.th. else
3) Right click CS:GO in Steam Library -> Properties -> Local Files tab -> Verify Integrity of Game Cache button and let it finish that including re-acquiring of broken files (this is required, because the game will crash without some cfg files.)
4) Start the game and see if version command produces output.

**Comment by dtugend** [comment]
Please also check if the version command works without HLAE, if it does and doesn't work with HLAE, then there might be an HLAE related problem.

**Comment by JonTrooper** [comment]
After completely removing my **autoexec** and resetting my **config** files the `version` command works..

```
] version
Protocol version 13499
Exe version 1.34.9.9 (csgo)
Exe build: 17:43:33 Jul 29 2015 (6102) (730)
```

This is annoying because I checked over my **autoexec** and **config** to check for something that could cause this, I haven't found any strange looking commands in both the files, do you have any idea what could be causing this?

Fixing the **cfg** would probably also get the `mirv` commands to work so I'll go ahead and remake my **autoexec** until you hopefully reply with a better solution.

**Comment by dtugend** [comment]
Well you could post your config on pastebin.com maybe (if it's not secret) and I could have a look, but I cannot check it before tomorrow.

**Comment by JonTrooper** [comment]
I just remade my **autoexec**, and turns out that it was causing the problem the whole time, some command/s made it not work for some reason, I'll try and find out what command was causing it.

`mirv_deathmsg` is working after remaking the **cfg**.

**Comment by dtugend** [comment]
Okay, please close the issue when you are done with solving the problem (would be good to know what was causing it, if you find out. As said I can try to help, you can post your autoexec on https://gist.github.com/ ).

**Comment by JonTrooper** [comment]
For some reason these commands are causing it.

```
con_filter_enable "1"
con_filter_text "damage"
gameinstructor_enable "0"
```

They make it so it prints in the console how much damage I've dealt to an enemy player and that's it.

**Comment by dtugend** [comment]
Thank you, hopefully this will help other people with a similar problem.
