### ISSUE TITLE
Not launching/opening

### ISSUE THREAD

**Issue by pascalworks** [advancedfx/advancedfx-prop#9]
First of all i dont know if this is the right place to post this, IF i posted it in the wrong place how can i remove it/ move it to another place where it belongs?

Since the update of 2.7.3.0 I cannot open Half-Life Advanved Effects it's pretty wierd, i opened task menager there were Three HLAE.exe's running all of them 108-112K when i tried to end procces to one of them it did nothing
I even rebooted my computer to check if that was the problem but it kept hapening i opened up task menager before running HLAE and ran it with and without administrator now this is the part where it gets wierd when i didnt run it with admin perms it only started 3 HLAE.exe's but when i ran it with admin it started/launched 5 HLAE.exe's  but still nothing happaned nothing poped up no window no nothing only that the program is running in Task menager

I had to go back to 2.6.8.2 and that ran perfectly fine, whats the problem here?
![1233423](https://cloud.githubusercontent.com/assets/16799771/12451337/0c9ea3c2-bf89-11e5-9df4-2b99eeed7798.png)

**Comment by dtugend** [comment]
It's fine to post here.
- Please do not run HLAE or CS:GO with admin rights, this is not required and can lead to problems.
- Where did you get the HLAE from, hopefully from the official page / this GitHub repository?
- Did you extract all files and folders from the download into a folder you like?

Now here comes the fun part:
- The only changes that should affect HLAE.exe are the Update GUIDs (3 short strings in the HLAE.exe) that I changed. (I checked with git diff.)

The only other things I can think of atm:
- The files got broken when/after extracting them
- You are using some antivirus that detects HLAE or one of it's components as virus (happend with 2 or 3 free Chinese anti viruses in the past) due to one of the update GUID strings used and blocks it and prevents it from exectuing properly.

If you want you can contact me live in HLAE QuakeNet webchat (see Contact page on http://www.advancedfx.org/contact/ ) or you can add me in Steam: http://steamcommunity.com/id/ripieces

**Comment by dtugend** [comment]
Also it might be helpful to know if you have any events from HLAE.exe / AfxGui in [Windows Event Viewer](http://windows.microsoft.com/en-us/windows/open-event-viewer) Application log.

**Comment by dtugend** [comment]
I need your feedback in order to solve this issue,
if there is no Feedback before 2016-02-04T00:00Z I will close the issue and assume the problem has been solved.

I am especially interested in this:

> Also it might be helpful to know if you have any events from HLAE.exe / AfxGui in [Windows Event Viewer](http://windows.microsoft.com/en-us/windows/open-event-viewer) Application log.

Also you can contact me in the ways mentioned in the first reply.

**Comment by dtugend** [comment]
As announced I am closing this issue due to lacking of required feedback from your side.

Feel free to contact me in one of the ways described in my replies or to re-open the issue, once you are able to provide feedback.
